[1]
firstPreference = "Web Development"
secondPreference = "App Development"
thirdPreference = "Development"
antiPreference= ['20 - Data Science Skilled Team - MPS', '11 - Cohorting & Data Linkage - Analytical Insights Service', '29 - Data Engineering', '3 - Nightingale squad']

[2]
firstPreference = "23 - Data Science / Business Intelligence"
secondPreference = "Data Visualisation"
thirdPreference = "Power BI"
antiPreference = ['6 - SDE Platform Team', '32 - Electronic Prescription Service (Team Epsilon)', '18 - 111 online', '31 - Child Protection Information Sharing (CP-IS)', '38 - Cyber Security Operations Centre (CSOC)']

[3]
firstPreference = "Python"
secondPreference = "Development"
thirdPreference = "Data Analytics"
antiPreference = ['27 - Vaccinations - National Booking Service', '8 - Analytical Services: Population Health, Clinical Audit and Specialist Care (Seacole squad)', '12 - Lovelace (in Archimedes tribe)', '13 - ITOC Onboarding / Development ', '28 - Analytical Insights']

[4]
firstPreference = "38 - Cyber Security Operations Centre (CSOC)"
secondPreference = "Cyber Security"
thirdPreference = "Development"
antiPreference = ['15 - DoS Integration', '37 - Specialist Security Services', '19 - 111 online', '0 - Babbage Squad - Archimedes Tribe', '25 - Data Science / TRE Data Wranglers']

[5]
firstPreference = "16 - Developer / DoS Features"
secondPreference = "Python"
thirdPreference = "Development"
antiPreference = ['40 - Data Security Center (DSC) Innovation and Delivery (I&D) Team', '23 - Data Science / Business Intelligence', '4 - Digital Transformation of Screening', '10 - Data Visualisation & Insights - Analytical Insights Service', '30 - UEC Data, Digital Urgent & Emergency Care']

[6]
firstPreference = "Development"
secondPreference = "App Development"
thirdPreference = "Web Development"
antiPreference = ['21 - Data Science / Artificial Data','16 - Developer / DoS Features', '35 - Primary Care Registration Management', '17 - Test / DoS Features / Live Service']

[7]
firstPreference = "Cyber Security"
secondPreference = "Python"
thirdPreference = "Machine Learning"
antiPreference = ['7 - Screening Programme (Digital Transformation of Screening and Live Screening Services)', '14 - DoS & DoS Integration team', '26 - Vaccinations Programme, Tech & Data Delivery Team', '39 - Collaboration Services Team - Centre of excellence', '22 - Data Science / RAP']

[8]
firstPreference = "Data Science"
secondPreference = "Python"
thirdPreference = "Pandas"
antiPreference = ['24 - Data Science / covid patient pathways', '9 - Lovelace Squad', '1 - Turing squad', '36 - Infra Ops']

[9]
firstPreference = "Python"
secondPreference = "Machine Learning"
thirdPreference = "Development"
antiPreference = ['5 - Bowel Cancer Screening', '28 - Analytical Insights', '30 - UEC Data, Digital Urgent & Emergency Care', '6 - SDE Platform Team']

[10]
firstPreference = "38 - Cyber Security Operations Centre (CSOC)"
secondPreference = "Cyber Security"
thirdPreference = "Python"
antiPreference = ['3 - Nightingale squad', '11 - Cohorting & Data Linkage - Analytical Insights Service', '12 - Lovelace (in Archimedes tribe)', '8 - Analytical Services: Population Health, Clinical Audit and Specialist Care (Seacole squad)', '25 - Data Science / TRE Data Wranglers']

[11]
firstPreference = "Development"
secondPreference = "Python"
thirdPreference = "Cyber Security"
antiPreference = []

[12]
firstPreference = "36 - Infra Ops"
secondPreference = "Python"
thirdPreference = "Data Visualisation"
antiPreference = []

[13]
firstPreference = "Web Development"
secondPreference = "Python"
thirdPreference = "Cyber Security"
antiPreference = []

[14]
firstPreference = "Web Development"
secondPreference = "App Development"
thirdPreference = "AWS"
antiPreference = []

[15]
firstPreference = "Reproducible Analytical Pipelines (RAP)"
secondPreference = "Data Visualisation"
thirdPreference = "Data Analytics"
antiPreference = []

[16]
firstPreference = "Data Science"
secondPreference = "Data Visualisation"
thirdPreference = "Data Analytics"
antiPreference = []

[17]
firstPreference = "Machine Learning"
secondPreference = "Python"
thirdPreference = "Development"
antiPreference = []

[18]
firstPreference = "Cyber Security"
secondPreference = "AWS"
thirdPreference = "Data Analytics"
antiPreference = []

[19]
firstPreference = "Development"
secondPreference = "Data Analytics"
thirdPreference = "Web Development"
antiPreference = []

[20]
firstPreference = "Cyber Security"
secondPreference = "Development"
thirdPreference = "AWS"
antiPreference = []

[21]
firstPreference = "38 - Cyber Security Operations Centre (CSOC)"
secondPreference = "Development"
thirdPreference = "Web Development"
antiPreference = []

[22]
firstPreference = "Python"
secondPreference = "Web Development"
thirdPreference = "SQL"
antiPreference = []

[23]
firstPreference = "Data Analytics"
secondPreference = "Data Visualisation"
thirdPreference = "Data Science"
antiPreference = []

[24]
firstPreference = "Web Development"
secondPreference = "App Development"
thirdPreference = "Development"
antiPreference = []

[25]
firstPreference = "13 - ITOC Onboarding / Development "
secondPreference = "Python"
thirdPreference = "Data Analytics"
antiPreference = []

[26]
firstPreference = "Cyber Security"
secondPreference = "Development"
thirdPreference = "AWS"
antiPreference = []

[27]
firstPreference = "Development"
secondPreference = "Web Development"
thirdPreference = "Machine Learning"
antiPreference = []

[28]
firstPreference = "Data Science"
secondPreference = "Python"
thirdPreference = "Data Analytics"
antiPreference = []

[29]
firstPreference = "Data Analytics"
secondPreference = "Data Visualisation"
thirdPreference = "Python"
antiPreference = []

[30]
firstPreference = "Data Analytics"
secondPreference = "Data Science"
thirdPreference = "Python"
antiPreference = []

[31]
firstPreference = "Python"
secondPreference = "Data Visualisation"
thirdPreference = "Data Analytics"
antiPreference = []

[32]
firstPreference = "Development"
secondPreference = "Reproducible Analytical Pipelines (RAP)"
thirdPreference = "Data Analytics"
antiPreference = []

[33]
firstPreference = "Python"
secondPreference = "Cyber Security"
thirdPreference = "Development"
antiPreference = []

[34]
firstPreference = "Data Analytics"
secondPreference = "Data Engineering"
thirdPreference = "Data Visualisation"
antiPreference = []

[35]
firstPreference = "Cyber Security"
secondPreference = "Data Analytics"
thirdPreference = "Python"
antiPreference = []

[36]
firstPreference = "Data Science"
secondPreference = "Data Analytics"
thirdPreference = "SQL"
antiPreference = []

[37]
firstPreference = "App Development"
secondPreference = "Web Development"
thirdPreference = "SQL"
antiPreference = []

[38]
firstPreference = "Data Analytics"
secondPreference = "Python"
thirdPreference = "Development"
antiPreference = []

[39]
firstPreference = "Data Science"
secondPreference = "Azure"
thirdPreference = "Development"
antiPreference = []

[40]
firstPreference = "Data Analytics"
secondPreference = "Big Data"
thirdPreference = "Python"
antiPreference = []
